on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build /p:Version=$VERSION
    - name: Test
      run: dotnet test --verbosity normal
    - name: pack nuget packages
      run: dotnet pack --output nupkgs /p:PackageVersion=$VERSION
    - name: upload nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k "$NUGET_TOKEN" -s https://api.nuget.org/v3/index.json
      env: 
        NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
